### ISSUE TITLE
GoogleCast.castMedia always starts casting at the beginning

### ISSUE THREAD

**Issue by aecorredor** [flextv/react-native-google-cast#11]
When using `GoogleCast.castMedia` and giving it a `playPosition` of whatever seconds to start casting at that position, it doesn't work, and just starts casting from the beginning. This is happening on android for me.

**Comment by petrbela** [comment]
We have the same issue on Android, too. Seems to work okay on iOS.

**Comment by aecorredor** [comment]
Just as an FYI, I tried passing it a different `streamDuration` too and it didn't pick it up either. It actually gets the correct duration (I guess from the media file).

**Comment by petrbela** [comment]
I don't remember what the `streamDuration` is for exactly (perhaps hls stream?). Will look into that, too.

**Comment by jedashford** [comment]
We'll be resting this within the week. I assume it's a quick fix and can take a look as we begin.

**Comment by jonnynfb** [comment]
Easy fix. You can see my PR #28

**Comment by jedashford** [comment]
Looks like this is merged in, should we close this?

**Comment by petrbela** [comment]
You're right.
