### ISSUE TITLE
player has by default mute button but cast is not muted so please check this bug

### ISSUE THREAD

**Issue by yogeshmoradiya121** [flextv/react-native-google-cast#21]
and in cast popuup always show no media selected

**Comment by petrbela** [comment]
Hi!

Can you please help me understand the exact issue? The cast popup has a slider to change the volume or mute it entirely. Is the problem you're describing the fact that it doesn't remember previous settings and always starts as unmuted? Or does changing the slider not update the volume on your TV?

> and in cast popup always show no media selected

Can you please upload a screenshot of what you're seeing and what you expect to be seeing?

Thanks!

**Comment by petrbela** [comment]
Please reopen at react-native-google-cast/react-native-google-cast/issues if it's still an issue.
