### ISSUE TITLE
Native Component for "RNGoogleCastButton" does not exist

### ISSUE THREAD

**Issue by birkanozekan** [flextv/react-native-google-cast#22]
On Android, I've imported the library, without problem.
import GoogleCast, { CastButton } from 'react-native-google-cast';

GoogleCast object works but when I add <CastButton /> component in render section, I got this error; "Native Component for RNGoogleCastButton does not exist"

"react": "16.4.1",
"react-native": "0.55.4",

**Comment by petrbela** [comment]
Hi! Did you install the library from npm? I just updated the readme; currently, you need to install directly from github.

**Comment by birkanozekan** [comment]
My package.json file is like this;

"dependencies": {
	...
	"react-native-google-cast": "https://github.com/flextv/react-native-google-cast/tarball/master",

**Comment by RahnRazamai** [comment]
> My package.json file is like this;
> 
> "dependencies": {
> ...
> "react-native-google-cast": "https://github.com/flextv/react-native-google-cast/tarball/master",

@birkanozekan maybe it you should change to this.     
"react-native-google-cast": "github:RahnRazamai/react-native-google-cast",

**Comment by birkanozekan** [comment]
I don't think it's about package url.
Files in my node_module/react-native-google-cast folder are up to date.

GoogleCast.getCastState() returns "NoDevicesAvailable" without error.

But GoogleCast.showIntroductoryOverlay() returns error "_reactNativeGoogleCast2.default.showIntroductoryOverlay is not a function"

And also when I add<CastButton/> into render function, I get this error; "Native Component for RNGoogleCastButton does not exist"

Tested with 7.0 and 8.0 android devices

My dependencies on build.gradle;
    compile project(':react-native-onesignal')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-image-crop-picker')
    compile project(':react-native-orientation')
    compile project(':react-native-keep-awake')
    compile project(':react-native-video')
    compile project(':react-native-google-cast')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:25.1.0"
    compile "com.google.android.gms:play-services-cast:15.0.1"
    compile "com.android.support:mediarouter-v7:25.1.0"
    compile "com.facebook.react:react-native:+"
