### ISSUE TITLE
framework not found GoogleCast

### ISSUE THREAD

**Issue by yuriydrobniy** [flextv/react-native-google-cast#29]
Hi! I have next error in Xcode while building project 
`ld: framework not found GoogleCast`
`clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Podfile
`target 'XXXX' do`
      ` . pod 'google-cast-sdk', '~> 3'`
      ` . pod 'FBSDKShareKit'`
      ` . pod 'FBSDKLoginKit'`
      ` . pod 'FBSDKCoreKit'`
`end`

**Comment by petrbela** [comment]
Are you sure you've opened xcworkspace, not xcproject?

**Comment by jedashford** [comment]
For me, missing in the instructions are to add 'libRNGoogleCast.a' to your project > Build Phases. Not sure if its the same message, but you do need to open XCode and make sure to link the library that was pulled in with the pod install.

**Comment by petrbela** [comment]
Please reopen at https://github.com/react-native-google-cast/react-native-google-cast/issues if it's still an issue.
