### ISSUE TITLE
Does not detect chromecast, button does not appear

### ISSUE THREAD

**Issue by hitaloramon** [flextv/react-native-google-cast#32]
Some cell phones can not find the chromecast, so the submit button does not appear, do you have any idea what it can be and how to solve it? As many users of chromecast 1 as of chromecast 2 reported that.

Sorry for my English

**Comment by joshjhargreaves** [comment]
I am seeing the same thing too actually on a test device, iPhone 7 Plus, iOS 12.1.

I just tried upgrading the google-cast-sdk to `4.3.0` - same issue. `GCKCastContext.sharedInstance castState` returns `nil`.

**Comment by joshjhargreaves** [comment]
It looks like in iOS 12, you need to add the capability `Access WiFi information` which I had missed as had only looked at this page on iOS 11.

https://developers.google.com/cast/docs/ios_sender/

 ![screen shot 2018-12-04 at 5 32 12 pm](https://user-images.githubusercontent.com/1807207/49477659-98ef6080-f7eb-11e8-973c-c2755a7d1de4.png)

**Comment by petrbela** [comment]
Please reopen at https://github.com/react-native-google-cast/react-native-google-cast/issues if it's still an issue.
