### ISSUE TITLE
How to use react-native-navigation with react-native-google-cast?

### ISSUE THREAD

**Issue by jedashford** [flextv/react-native-google-cast#5]
It looks like you specific mention this here:

> If you already extend other class than ReactActivity (e.g. if you use react-native-navigation) or integrate React Native in native app, make sure that the Activity is a descendant of android.support.v7.app.AppCompatActivity. Then add CastContext.getSharedInstance(this); to your Activity's onCreate method (this lazy loads the Google Cast context).

If MainActivity extends NavigationActivity and I add `CastContext.getSharedInstance(this);` to the `onCreate` method, then I get build errors. Am I missing something else?

build errors (I assume this is due to not extending GoogleCastActivity. Does that mean I must extend GoogleCastActivity?):

```/android/app/src/main/java/com/vidangel/MainActivity.java:16: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.```

**Comment by petrbela** [comment]
I've only tested it briefly but you should be able to make it work without extending GoogleCastActivity.

What method is the `@Override` on?

**Comment by petrbela** [comment]
To get the Cast button working I think you need to extend either `FragmentActivity`, `GoogleCastActivity`, or `AppCompatActivity`.

Please reopen at https://github.com/react-native-google-cast/react-native-google-cast/issues if it's still an issue.

**Comment by petrbela** [comment]
~Hmm also initializing the cast context in `MainApplication` instead of `MainActivity` as suggested by #25 might help.~ That throws `java.lang.IllegalStateException: The activity must be a subclass of FragmentActivity`.
